baseURL = "https://avi-d-coder.github.io/"
title = "Concise Thought"
languageCode = "en-us"
theme = "hyde-hyde"

paginate = 8
paginatePath = "page"

googleAnalytics = "UA-119786476-1"
disqusShortname = "avi-ds-concise-thoughts"


copyright = "(c) 2018 Avi ד."

[params]
    author = "Avi ד"
    title = "Concise Thought"
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    email = "avi.the.coder@gmail.com"
    github = "Avi-D-coder"

