baseURL = "https://avi-d-coder.github.io/"
title =  "Posts"

languageCode = "en-US"
MetaDataFormat = "toml"
theme = "hyde-y"

paginate = 8
paginatePath = "page"

disqusShortname = "avi-ds-concise-thoughts"

copyright = "(c) 2018 Avi ד."

[taxonomies]
    tag = "tags"

[author]
    name = "Avi ד"
    email = "avi.the.coder@gmail.com"

[params]
    brand = "Avi ד's concise thoughts"
    topline = "Need&nbsp;good&nbsp;dev? I&nbsp;am&nbsp;available for hire anywhere in&nbsp;the United&nbsp;States."
    sidebar = "left"
    highlight = "sunburst"
    github = "Avi-D-coder"
    rss = false
    googleAnalytics = "UA-119786476-1"
