baseURL = "https://avi-d-coder.github.io/"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "hyde-y"

paginate = 8
paginatePath = "page"

copyright = "(c) 2018 Avi ד."

[author]
    name = "Avi ד"
    email = "avi.the.coder@gmail.com"

[params]
    brand = "Avi ד's concise thoughts"
    topline = "Need a good dev? I am available to hire anywhere in the United States."
    sidebar = "left"
    highlight = "sunburst"
    github = "Avi-D-coder"
    rss = false
    googleAnalytics = "UA-119786476-1"
